### ISSUE TITLE
Product Question

### ISSUE THREAD

**Issue by SteveYurka** [imojiengineering/imoji-ios-sdk#10]
Hey Imoji team,

Imoji is really awesome in general! Thank you for the service and your work.

I was wondering if you had any intention to provide a borderless (or rendering option) version again, now that it is been removed since changing the SDK to work only with the REST API.

There are times when having the classic white border significantly enhances things... such as inside a chat, or using it as an emoji in the classic sense. 

However, when applying imoji's to images and videos, the border is a very poor effect in comparison. 

Please do some tests yourselves, don't just take my word for it, I challenge you to get 10 Images or Videos, and place a white bordered imoji vs a borderless version on them.

Here is an example off your website: http://imoji.io/assets/images/sdk/web_sdk_create.png, of using the white bordered version to replace peoples heads. 

The effect of having a border make it looks like a singular object, playful & fun, and therefore more emoji like (which as I said, is great inside something like chat).

I would say that in comparison, when someone is using the imoji to do something like replace a head, put a hat on, or put an object in their mouth, etc (which looks like a very large use case, based on the ratio of peoples heads to random objects, when looking through your most popular results, there are LOTS of heads), the effect of having the head look more realistic, and without the border, makes for an infinitely better image/video

You can even draw a parallel example when looking at Snapchat's new live filters, they have tried to blend the filer/overlay into the image as much as possible, rather than making it severely stick out on top.

A bunch of our users have noticed this and we now have to remain on your old SDK, which I am sure is going to end up unsupported soon.

Thanks

**Comment by nkhoshini** [comment]
Hi Steve, thanks for the feedback and big apologies for the late reply here.
For what it's worth, we moved the rendering of the images to the server for speedier rendering. In the process we lost the ability for SDK users to customize the border and shadow properties. We currently support bordered and unbordered rendering in IMImojiRenderingOptions. We will look to add more flexibility via a server driven Rest API soon.

Thanks!
