### ISSUE TITLE
fetchImojisByIdentifiers returns "Unable to download (null) error code: -1002"

### ISSUE THREAD

**Issue by MoralAlberto** [imojiengineering/imoji-ios-sdk#13]
I'm trying to fetch imojis with one identifier. The identifier used has been retrieved from a previous call ```getImojiCategoriesWithClassification``` ("heylo", "tumblr", etc)

the code:
```swift
session = IMImojiSession.init()
session.fetchImojisByIdentifiers([self.identifier]) { (imoji: IMImojiObject?, result: UInt, error: NSError?) -> Void in
            print("Result \(imoji)")
}
```

and I always receive the same error,

▿ Optional(Error Domain=IMImojiSessionErrorDomain Code=1 "Unable to download (null) error code: -1002" UserInfo={NSLocalizedDescription=Unable to download (null) error code: -1002})

any clue?

 thanks in advance!

**Comment by MoralAlberto** [comment]
Solved. I was using the incorrect call, now I'm using, and **searchTerm** is the category identifier.

 ```public func searchImojisWithTerm(searchTerm: String?, offset: NSNumber?, numberOfResults: NSNumber?, resultSetResponseCallback: IMImojiSessionResultSetResponseCallback, imojiResponseCallback: IMImojiSessionImojiFetchedResponseCallback) -> NSOperation```

**Comment by nkhoshini** [comment]
Hi @MoralAlberto sorry for the confusion there! In case you run into anything else, our fully featured swift example should help:

https://github.com/imojiengineering/imoji-ios-sdk-ui/tree/master/Examples/Artmoji

Thanks!
