### ISSUE TITLE
No IMCategoryFetchOptions.h in the ImojiSDK.h

### ISSUE THREAD

**Issue by pilot34** [imojiengineering/imoji-ios-sdk#18]
When import only `#import <ImojiSDK/ImojiSDK.h>` and use `IMCategoryFetchOptions` I have compilation error:

![error](https://monosnap.com/file/QyKT7Gf5k0aSrNGa5ZKE1xIM9FDJrC.png)

When I import `#import <ImojiSDK/IMCategoryFetchOptions.h>` error is gone. So I think you need import that header in your umbrella header.

**Comment by nkhoshini** [comment]
Nice catch! Fix coming…

**Comment by nkhoshini** [comment]
Fixed in version 2.3.1
