### ISSUE TITLE
Using ImojiSDK in App Extension

### ISSUE THREAD

**Issue by pilot34** [imojiengineering/imoji-ios-sdk#4]
Hello. Some problems with ImojiSDK in iOS keyboard extension.

In App Extension we can't use [UIApplication sharedApplication] and so on. 
Bolts/Links isn't compiled in app extension target.  ![](http://monosnap.com/image/5w5Ogi0xVIqM7Qcj4P8oKGkIVa6tux.png)

But without it ImojiSDK isn't compiled too. It uses BFAppLinkNavigation and BFAppLinkTarget.

How can I use ImojiSDK in keyboard extension? Maybe you can build light version of lib without app links  features?

I can fork Bolts and remove sharedApplication calls, but maybe exists better solution.

**Comment by nkhoshini** [comment]
Greetings, thanks for the issue. The problem maybe alleviated by specifying ```use_frameworks!```  in your Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
```

This'll allow the dependent libraries to be linked in as Frameworks rather than static libraries.

**Comment by pilot34** [comment]
Hmm, It was not easy to compile and run with frameworks but it really works now!
Thanks!
What did happen? Why does it work?
Runtime loads each class separately only when it is needed?

**Comment by nkhoshini** [comment]
Yup pretty much, not enforcing use frameworks will compile all sources into a static library. I'll make sure to add this to the documentation, thanks so much for the feedback!
