### ISSUE TITLE
Memory usage while rendering images

### ISSUE THREAD

**Issue by pilot34** [imojiengineering/imoji-ios-sdk#7]
Hello!

I'm implementing keyboard with imoji stickers. And cannot create simple collection view with images without memory crashes.

You haven't got memory leaks, but memory isn't cleaned while user scrolls collection view. And if there are many images to render: it will crash. I tried wrap you renderer with custom queue to cancel rendering when scrolling, but no progress with it.

I forked your keyboard sample to reproduce this crash. I added more images to scroll view and enlarge image size a bit. It crashes even on iPhone 6. You should run keyboard and perform fast scroll forward (and maybe back if it won't crash)
https://github.com/pilot34/imoji-ios-sdk-ui

Here is example screenshot from Instruments. Huge memory usage. It isn't cleaned while scrolling http://monosnap.com/image/h2OiZGYfvEtRv4tdAMLSMufVpKnIIs.png

I tried Fleksy keyboard (they implemented Imoji too) and they have same crash if fast scroll forward and back in every collection view with imoji.

Thank you. Hope it can be fixed. And it's a pity, that you don't provide sources.

**Comment by nkhoshini** [comment]
Hi there! Thanks for reporting this. Off the top of my head I'm uncertain what would be causing the memory issue but it should be easy to diagnose with the fork you've provided. The render process does use a bit of memory while rendering however that operation is done in a serial background queue so regardless of the number of render requests you make it should not process them in parallel jeopardizing memory usage. I will have to dig into that some more and see what's going on.

We are open to option of opening the source code however at the moment it's tied to our main iOS application and requires us to isolate the SDK code first.

**Comment by nkhoshini** [comment]
Hello, I've just pushed an update to the SDK. This new version is completely open source and uses our REST API's. In the process of updating we removed support for custom borders and shadows however hope to have that soon exposed in our REST API's. 

You should find the performance to be significantly improved now that the heavy lifting has been moved to the server. 

Thanks for the feedback!!

**Comment by pilot34** [comment]
Thanks, that's great!

There are some problems with compiling keyboard extension after updating (in your sample too) but I finally made it compiling.

Now canceling operations works perfect when reusing cells and there is no memory peaks. Thank you for such opportune update and for opened source!
