### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by csaby02** [imojiengineering/imoji-ios-sdk#9]
Hi,

We found a crash which seems to be reproducible all the time.
Steps to reproduce:
1. Enable Wifi
2. Set clientId and APIToken
3. Create an imojiSession and set it's delegate
4. Set the imojiSession's delegate to nil
5. Set the imojiSession to nil
6. Turn off Wifi

The app will crash with : "networkStatusChanged:]: unrecognized selector sent to instance" in IMReachabilityClient.m line 86 - it seems that an observer wasn't removed when the imojiSession was deallocated.

**Comment by nkhoshini** [comment]
Hi, thanks for the report. What version of the SDK are you using? We removed reachability code in version 0.1.17

**Comment by csaby02** [comment]
I've used an earlier version. Thank you for your fast response.
